<?php

namespace WP\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

//    public function getUsersByRoleQB($role) {
//        $qb = $this->createQueryBuilder('u');
//
//        return $this->createQueryBuilder('u')->join('u.roles','r')
//            ->where($qb->expr()->in('r.role',$role))
//            ->orderBy('u.company', 'ASC');
//    }

    public function getUsersByRoleQB($role) {
        $qb = $this->createQueryBuilder('u')

            ->orderBy('u.company', 'ASC');

        $qb->add('where', $qb->expr()->in('u.role', array($role)));
        return $qb
//            ->getQuery()
//            ->getResult()
            ;

//            ->where($qb->expr()->in('r.role',$qb->expr()->literal($role)))

    }

}
