wp_whitepaper_homepage:
    path:     /{page}
    defaults: { _controller: WPWhitepaperBundle:Whitepaper:index, page: 1 }
    requirements:
        page: \d*

wp_whitepaper_add:
    path:     /add
    defaults: { _controller: WPWhitepaperBundle:Whitepaper:add }

wp_whitepaper_view:
    path:     /view/{id}
    defaults: { _controller: WPWhitepaperBundle:Whitepaper:view }

wp_whitepaper_edit:
    path:     /edit/{id}
    defaults: { _controller: WPWhitepaperBundle:Whitepaper:edit }

wp_whitepaper_delete:
    path:     /delete/{id}
    defaults: { _controller: WPWhitepaperBundle:Whitepaper:delete }



wp_editor_homepage:
    path:     /editor/{page}
    defaults: { _controller: WPWhitepaperBundle:Editor:index, page: 1 }
    requirements:
            page: \d*

wp_editor_add:
    path:     /editor/add
    defaults: { _controller: WPWhitepaperBundle:Editor:add }

wp_editor_edit:
    path:     /editor/edit/{id}
    defaults: { _controller: WPWhitepaperBundle:Editor:edit }

wp_editor_delete:
    path:     /editor/delete/{id}
    defaults: { _controller: WPWhitepaperBundle:Editor:delete }