<?php

namespace WP\WhitepaperBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\QueryBuilder;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EditorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorRepository extends EntityRepository
{

    public function getEditors($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('e')
//            ->leftJoin('a.image', 'i')
//            ->addSelect('i')
//            ->leftJoin('a.categories', 'c')
//            ->addSelect('c')
//            ->where('w.published = :published')
//            ->setParameter('published', true)
            ->orderBy('e.name', 'ASC')
            ->orderBy('e.id', 'DESC')
            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }

}
