<?php

namespace WP\WhitepaperBundle\Entity;

use Doctrine\ORM\EntityRepository;

use Doctrine\ORM\QueryBuilder;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * WhitepaperRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhitepaperRepository extends EntityRepository
{

    public function getWhitepapers($page, $nbPerPage)
    {
        $query = $this->createQueryBuilder('w')
//            ->leftJoin('a.image', 'i')
//            ->addSelect('i')
//            ->leftJoin('a.categories', 'c')
//            ->addSelect('c')
            ->where('w.published = :published')
            ->setParameter('published', true)
            ->orderBy('w.updated_at', 'DESC')
            ->orderBy('w.id', 'DESC')
            ->getQuery()
        ;

        $query
            ->setFirstResult(($page-1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
        ;

        return new Paginator($query, true);
    }

}
